### ISSUE TITLE
Github actions builder

### ISSUE THREAD

**Issue by avilaton** [UniTime/unitime#101]
Hi, I'm trying to learn about the project by adding a github action to build it. I forked and added a few things to it, would you be able to help me out? It is timing out after a long while, please have a look here
https://github.com/avilaton/unitime/runs/4643836519?check_suite_focus=true

**Comment by avilaton** [comment]
Here is one error I received earlier
```Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project unitime: Compilation failure: Compilation failure: 
Error:  /home/runner/work/unitime/unitime/target/src/org/unitime/timetable/util/MemoryCounter.java:[157,30] Unsafe is internal proprietary API and may be removed in a future release
Error:  /home/runner/work/unitime/unitime/target/src/org/unitime/timetable/util/MemoryCounter.java:[167,27] Unsafe is internal proprietary API and may be removed in a future release
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: Process completed with exit code 1.
```

**Comment by tomas-muller** [comment]
Please try again. We were in the process of updating the Log4j dependency and the Maven build did not work for a few days (the Ant build that is used to make official builds that are available at [builds.unitime.org](https://builds.unitime.org/) has worked fine).

**Comment by avilaton** [comment]
Thanks Thomas, I replayed it and the error above is gone. It was able to make a lot of progress, it now failed with 
```
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ unitime ---
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.pom
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52:17 min
[INFO] Finished at: 2022-01-05T14:11:38Z
[INFO] Final Memory: 27M/340M
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.4:jar (default-jar) on project unitime: Execution default-jar of goal org.apache.maven.plugins:maven-jar-plugin:2.4:jar failed: Plugin org.apache.maven.plugins:maven-jar-plugin:2.4 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-jar-plugin:jar:2.4 -> org.apache.maven:maven-archiver:jar:2.5: Failed to read artifact descriptor for org.apache.maven:maven-archiver:jar:2.5: Could not transfer artifact org.apache.maven:maven-archiver:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): Connection timed out (Read failed) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Error: Process completed with exit code 1.
```
Here is the full build log, https://github.com/avilaton/unitime/runs/4715033008?check_suite_focus=true, maybe I'll have time to look into why this could be failing later on but if you have a good hint, that helps.

**Comment by tomas-muller** [comment]
The error does not seem to be related to UniTime per se:
```
Could not transfer artifact org.apache.maven:maven-archiver:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): Connection timed out (Read failed)
```
and the URL for the org.apache.maven:maven-archiver:pom:2.5 artifact seems to work fine: [https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.pom](https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.pom)

In any case, I have updated the maven-jar-plugin version to the latest one (3.2.0) in commit 034bb8f.

**Comment by avilaton** [comment]
I submitted https://github.com/UniTime/unitime/pull/104, it takes a while for it to build, I wonder if there is anything I can do to make it faster.

**Comment by tomas-muller** [comment]
I think it would be sufficient to run this on the master branch for now -- that is the UniTime 4.6 development branch. The only other branch where this would make sense would be maint_UniTime45 for the current production version (UniTime 4.5) and perhaps maint_UniTime44 for the previous one (UniTime 4.4). These are the branches for which we do the nightly builds that are available at [builds.unitime.org](https://builds.unitime.org/).

Please note that the maint_UniTimeXX will not have the POM file updated with the recent versions like I did not on the master branch.

Also, in order to be able to accept the pull request, we need you to have signed the Contributor License Agreement (CLA) signed with the Apereo Foundation -- see [www.apereo.org/licensing/agreements](https://www.apereo.org/licensing/agreements) for more details.

**Comment by tomas-muller** [comment]
Pull request #104 has been merged.
