### ISSUE TITLE
change Instructional Offerings Subject Abbreviation to title

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [UniTime/unitime#111]
is there change Instructional Offerings Subject Abbreviation to title
![image](https://user-images.githubusercontent.com/46826627/172771658-62f0f1ff-0da0-4a48-8511-920e74189d22.png)

![image](https://user-images.githubusercontent.com/46826627/172771787-2a455be7-7469-4520-9654-97d903c8f83b.png)

**Comment by tomas-muller** [comment]
There are currently no options (or plans) to change the Subject list box on the Instructional Offerings page to show subject area titles instead of abbreviations.

**Comment by Abdulaziz-KTA** [comment]
how to make like image same abbv different department in subject Area?
![image](https://user-images.githubusercontent.com/46826627/173217280-9a481a52-a841-4323-b1c9-2d644de2bc38.png)

**Comment by tomas-muller** [comment]
Subject area abbreviations must be unique. UniTime should not allow for the subject areas with the same abbreviation.
