### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by charlesmwashashu** [UniTime/unitime#112]
Greetings,

Awesome project it is!

Given the scenario below, is it possible to have the **instructors** automatically receive **email notifications** based on their respective **class assignments start and end times** ?.

Lets say an Instructor has been assigned a class on Mondays starting at 1000hrs and ends at 1200hrs, Based on the **class start time** and **end time**, I would then like to;

1.  Automatically notify the instructor about the **class details / venue / room** just before the class start time
2.  Automatically share an assessment link via his/her email when the class ends so as to get feedback on the particular room features. i.e. if the overhead projectors, whiteboards, chalkboards are in order/faulty

Thanks

**Comment by tomas-muller** [comment]
UniTime does not send such emails at the moment. It would be fairly easy to create an HQL report that would list all classes starting in the next hour (or that have ended in the last hour) that could feed some outside script that would run (e.g., every half hour) and send the appropriate emails.

For example, if a new [Course Report](https://help.unitime.org/course-reports) is created (see Courses > Reports page), it is possible to download the output in CSV or JSON format using our [exports API (see HQL Reports section)](https://bit.ly/unitime44exports).
