### ISSUE TITLE
I have run the solve and it has stopped at 80.85%, I am trying to view what the timetable looks like in the timetable grid option (courses->course timetabling->timetable grid) when I run a search am gettting a Failed to load timetables: null error. How can I resolve this?

### ISSUE THREAD

**Issue by EricoMutonks** [UniTime/unitime#119]

**Comment by tomas-muller** [comment]
Do you have the default date pattern configured? It can be configured on the Administration > Academic Sessions > Academic Sessions page or Administration > Academic Sessions >  Date Patterns?

**Comment by EricoMutonks** [comment]
I created date patterns and assigned them to the courses as I was offering the courses. Am I suppose to create use a default date pattern?

But when I go to Administration > Academic Sessions > Academic Sessions page it says that No date patterns are available for this academic session

**Comment by EricoMutonks** [comment]
But when I go to Administration > Academic Sessions > Date Patterns tthe date patterns that I created have green ticks showing that I have used the the offered courses

**Comment by tomas-muller** [comment]
You need to click on the academic session, and on the Edit Academic Session page select one date pattern as default. Or, on the Date Patterns page, click on the date pattern that you want to make default and then click on the Make Default button.

This is typically the data pattern covering all the standard weeks of your semester. This date pattern will be used as a date pattern for all classes that do not have a particular date pattern selected directly on the class or on the scheduling subpart. It is also used by the Timetable Grid page to populate the available weeks in the Filter (hence the null error when there is no default date pattern).

**Comment by EricoMutonks** [comment]
I have made the date pattern I'm using to be default. It was worked successfully. 

Thank you so much for your assistance.
