### ISSUE TITLE
Can a manual timetable be created in unitime?

### ISSUE THREAD

**Issue by EricoMutonks** [UniTime/unitime#120]

**Comment by tomas-muller** [comment]
You could really really really benefit from reading the Course Timetabling Data Entry and Course Timetabling Solver manuals (see Help > Manuals).

You can fix a room at a particular time and/or room by requiring that time and/or room. You can also make manual changes to the timetable using the [Suggestions](https://help.unitime.org/suggestions) page. You need to have the date loaded into the solver, but the solver is only used to provide suggestions and check the conflicts.

Once a solution is saved and committed, manual changes can also be made using the [Class Assignment](https://help.unitime.org/class-assignment) page (no need to load the data into the solver), using the Class Assignment button on the [Class Detail](https://help.unitime.org/class-detail) page.
