### ISSUE TITLE
Could not create a DBCP pool (at DBCPConnectionProvider.java:181) 

### ISSUE THREAD

**Issue by kundo-siko** [UniTime/unitime#122]
Cant seem to figure out why i keep getting this error. followed all the installation instructions but was the site loads on localhost, i am greeted with a login screen and a message that says
"UniTime 4.5.177 failed to start up properly, please check the application log for more details."
SQLNestedException: Cannot create PoolableConnectionFactory (Communications link failure The last packet successfully received from the server was 976 milliseconds ago. The last packet sent successfully to the server was 968 milliseconds ago.) (at BasicDataSource.java:1549) 

....
how can i resolve this?
![Screenshot (10)](https://user-images.githubusercontent.com/63473065/187374962-7d4a9a4b-5fc2-4f76-89c3-33a8c89cfe58.png)

**Comment by tomas-muller** [comment]
The error seems to be related to the following error:

CommunicationsException: SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

which suggests that MySQL is trying to use an SSL connection (which is the default for MySQL 8.0, but usually not 5.7).

Anyway, in the unitime.properties file (see [here](https://help.unitime.org/installation#h.cn0eyym49zu1)), could you try to add the following line and restart the Tomcat?
```
connection.url=jdbc:mysql://localhost:3306/timetable?useSSL=false
```
this should disable the SSL connection. Alternatively, you can try to set enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2 instead (see [here](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-usagenotes-known-issues-limitations.html) or [here](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html)), that is 
```
connection.url=jdbc:mysql://localhost:3306/timetable?enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
```

**Comment by kundo-siko** [comment]
Thanks, was able to solve the problem by downloading a higher version of MySQL JDBC driver.
