### ISSUE TITLE
Import data and configuration in unitime

### ISSUE THREAD

**Issue by shreo1992-beep** [UniTime/unitime#123]
Dears

is it possible to import data or configurations to unitime in xml or csv i have already found in the link of xml interfaces that there are some features that can be imported like the academic session setup but can we do the same in the other features for example 

room type located in Administration->other->Room Type is there an option to import data to it in csv or xml format

kindly check the attached file it contains some samples 

[Implementation sheets.xlsx](https://github.com/UniTime/unitime/files/9467942/Implementation.sheets.xlsx)
thanks & best regards

**Comment by tomas-muller** [comment]
We currently do not have an XML to import room types and room features. These would have to be entered manually, or someone would have to write a [script](https://help.unitime.org/scripts) to import them from a custom format (which could be a CSV or an XML, for example).

The buildings and rooms can be imported using the [Rooms XML](https://www.unitime.org/interface/buildingRoomImport.xml) format, including their type and (global) room features. Please note that the rooms do not get updated automatically with the import; once the file is imported, you must go to Administration > Academic Sessions > Buildings and press the Update Data.

Also, by default, it will only add rooms that do not exist in the current academic session. If you need the update to change the existing rooms, you need to set the unitime.external.room.update.existing application property (on the Administration > Defaults > Configuration page) to true.

Similarly, an update of existing room features can be enabled by setting the parameter unitime.external.room.update.existing.features to true. The room feature must already exist in UniTime (as a global room feature) with either the roomFeature.feature attribute matching the room feature abbreviation or the roomFeature.value matching the room feature name.
