### ISSUE TITLE
Academic Session Dates Being Updated without Clicking Update Button

### ISSUE THREAD

**Issue by shaftain** [UniTime/unitime#126]
If we open an existing academic session and make some changes in dates, particularly 'Session Start Date' or 'Event Start Date' and then click Back button, without first clicking Update button, the system stores changes. Instead, it should store changes only when user clicks Update button.

**Comment by tomas-muller** [comment]
Fixed in UniTime 4.7 (build 60 or later) and UniTime 4.6 (build 99 or later)

**Comment by shaftain** [comment]
Thanks for the quick fix :)
