### ISSUE TITLE
Filter Timetable by Subject Area (in the Timetable Grid)

### ISSUE THREAD

**Issue by mndeto** [UniTime/unitime#14]
This Project is amazing! Thumbs up!
Could it be possible to add "subject area" in the "Resource" dropdown so as to enable filtering by Subject areas?

![filter by subject area](https://cloud.githubusercontent.com/assets/14832213/16454161/41d6651c-3e18-11e6-999c-6a53801664f4.png)

**Comment by tomas-muller** [comment]
This feature has been implemented in commit db3a2b858a790d059d1126b5d390454dbfd824c2.

**Comment by mndeto** [comment]
Thank you Tomas.

Kind regards,

Kind regards,
Martin
