### ISSUE TITLE
Customizing the timetable grid.

### ISSUE THREAD

**Issue by ahmad007** [UniTime/unitime#156]
Is it possible to change the timetable grid to start from any time rather than 7:30a using a GUI option? Or Should it be changed programmatically?

Also, is it possible to change the timetable grid unit to be 1 hour instead of 30 minutes using a GUI option?

**Comment by tomas-muller** [comment]
The start time, end time, and increment for each selection on the Times dropdown of the Timetable page can be changed using the unitime.timeGrid.timesX application properties (see Administration > Defaults > Configuration)

You can modify (or create another) time window (Times dropdown in the Filter on the Timetable page) using the unitime.timeGrid.timesX application properties (X is a number starting with one). The defaults are:

```
unitime.timeGrid.times1=Daytime|90|210|6
unitime.timeGrid.times2=Evening|210|276|6
unitime.timeGrid.times3=Daytime & Evening|90|276|6
unitime.timeGrid.times4=All|0|288|6
```

The format is name|first slot|last slot|increment, e.g., Daytime|90|222|6 means starting at 7:30 am, ending at 6:30 pm, in half-hour increments. All time slots are 5 minutes long and start at midnight.

So, for instance, if you want to change the Daytime & Evening times, create a new application property unitime.timeGrid.times3 and set it to what you need (using the Administration > Defaults > Configuration page). If you want to create new options, create property unitime.timeGrid.times5, unitime.timeGrid.times6, and so on.
