### ISSUE TITLE
Displaying class external ID to the course timetabling pages

### ISSUE THREAD

**Issue by rafati** [UniTime/unitime#16]
It will be really helpful if the class external ID can be displayed in the course timetabling pages:
UniTime/solutionReport.do
UniTime/timetable.do
UniTime/assignedClasses.do
UniTime/unassigned.do
UniTime/solutionChanges.do
UniTime/suggestions.do

**Comment by tomas-muller** [comment]
To show class external IDs, set the application configuration property unitime.solver.showClassSuffixes to true (defaults to false).

Implemented in UniTime 4.2, build 77 onwards.
