### ISSUE TITLE
Question about students groups

### ISSUE THREAD

**Issue by stgrzegorz** [UniTime/unitime#167]
Hello,
I didn't found how can i add students to the software base. Is it possible to do it by me?
At my university students dont select subjects, but programme is uniform for all students.
From this reason i wanted to created students groups by myself.
Thank you in advance.

**Comment by tomas-muller** [comment]
Students cannot be created directly in UniTime. We expect students to be imported into UniTime from a Student Information System. It is possible to import a student using our XML interface (see [http://www.unitime.org/uct_interfaces.php](http://www.unitime.org/uct_interfaces.php), in particular the [Students XML](https://www.unitime.org/interface/studentInfoImport.xml) or the [Student course requests XML](https://www.unitime.org/interface/woebegonStudents.xml) format).

You may also take a look at the curricula (see Courses > Course Timetabling > [Curricula](https://help.unitime.org/curricula)) as an alternative means of entering student demand data. A curriculum defines a list of courses that a particular group of students (identified by their academic area, major, and classification) need to take. You can define your own academic areas, majors, and classifications to fit your needs. Especially the classification can be a semester or a year of study (e.g., First Year, Second Year, etc.), or just an arbitrary grouping within the major (e.g., if you need to split each program into groups of students of a certain size).

**Comment by stgrzegorz** [comment]
Thank you for your advice.

**Comment by stgrzegorz** [comment]
I followed the instructions for importing students and I already have them in the database.
Is it possible to assign students or groups directly to a course without enrollment?

**Comment by tomas-muller** [comment]
You can import student course requests with the [Student course requests XML](https://www.unitime.org/interface/woebegonStudents.xml) format. You can use it only to import student course requests or to import students as well (when the `updateDemographics` element is included).

It is also possible to enter student course requests directly in UniTime using the [Student Course Requests](https://help.unitime.org/student-course-requests) page -- students may be allowed to fill the course requests themselves. This pre-registration needs to be enabled by setting the academic session status into one that allows for Course Requests in the Student Scheduling section (see Administration > Academic Sessions > Academic Sessions and Administration > Other > Status Types pages).

Student groups can be edited, including their students, on the Administration > Academic Sessions > Student Groups page. In course timetabling, student group reservations are only used to restrict students to certain course configurations and/or classes. For this to work, the student group has to be associated with some students that also do request the course (e.g., using Student Course Requests as student course demands).

Alternatively, it is also possible to rely on student group reservations to provide student demand data. In this case, the student groups must have the Expected Students parameter filled in and the `General.StudentGroupCourseDemands` solver parameter must be created and set to true. You can do that on the Administration > Solver > Parameters page, using the Add Solver Parameter button with the following parameters:
<img width="995" alt="111996872-bced2200-8b1a-11eb-9790-5786df61d03b" src="https://github.com/UniTime/unitime/assets/10631634/cff66d48-adb6-4c9c-a8b5-0316f674a060">
