### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DoanhTran03** [UniTime/unitime#171]
Good morning Mrs. Muller,
I am currently trying to install unitime but has the following error:
![image](https://github.com/UniTime/unitime/assets/103083272/275063c9-4463-43f1-b1c6-689ea8d66a4b)

The versions on my local machine is as following:
Tomcat version 8.5.95	
unitime version 4.7 	
MySQL Connector 8.2.0		
MySQL 8.2		
Complier: Java JDK version 21.0.1
Operating System: Windows 10 Pro

I have followed the instruction on the website including copy war file of unitime to tomcat and place jar file of sql connector to library of tomcat.
I would be appreciated if you could help me resolve the above issue

Sincerely,
Ngoc
Ngoc Doanh Tran

**Comment by tomas-muller** [comment]
Duplicate to #174
