### ISSUE TITLE
Student Registration Error

### ISSUE THREAD

**Issue by vaibhavi012** [UniTime/unitime#178]
Hello @tomas-muller ,
May I know why am I getting this error. Please help me in resolving this.

![image](https://github.com/user-attachments/assets/89596ffd-e110-4410-b30c-d7c84dc540c1)

And also students conflicts are not showing up and not getting resolved in the main solver, courses>course timetabling>solver.

**Comment by tomas-muller** [comment]
UniTime have deadlines on when a course can be added, modified, or removed from a student schedules. These are relative to the first meeting to the class and defined in the number of weeks (e.g., it is usually possible to add a class no later than during the first week of the class) and can be defined on the Academic Sessions page (see the Add/Edit Academic Session page) or modified for a particular offering (see Edit Course Offering page). It is also possible to disable these enrollment deadlines completely by setting the unitime.enrollment.deadline property to false on the Administration > Defaults > Configuration page.

Please provide more details about the second issue. What student course demand data are you using? Do you have the Course Timetabling Solver page (and the Student course demand parameter) set accordingly?

**Comment by vaibhavi012** [comment]
What parameters should be set to run the Timetabling Solver page so that it minimizes the student conflicts. In my case the students are not being loaded in the timetabling solver. It would be helpful if you could give me some idea about it.

**Comment by tomas-muller** [comment]
Minimization of student conflicts is one of the core optimization criteria for the solver (it does not need to be enabled). However, depending of what student course demands you are using (these could be last year's student course enrollments, curricula, or the actual student course requests), you need to set the **Student course demand** parameter on the [Course Timetabling Solver](https://help.unitime.org/course-timetabling-solver) page. Please see the page documentation at https://help.unitime.org/course-timetabling-solver for more details about the possible values of this parameter and what they mean (what data are expected to be entered and/or imported into UniTime).
