### ISSUE TITLE
Error with data exchange.

### ISSUE THREAD

**Issue by rafati** [UniTime/unitime#24]
I am getting the error below when trying to import a list of courses through the data exchange feature. Attached is the file I am trying to import. 
[Sample.txt](https://github.com/UniTime/unitime/files/790202/Sample.txt)

This feature was working fine in version 4.1, so it may be an issue with version 4.2. I am using the latest build "4.2.101 built on Sat, 11 Feb 2017"
Best Regards,

Importing S2017-courses-N-with-Schedule.php (4).xml (747 bytes)...
  --Transaction started.
offered status changed
added course: BAND 201
added credit: 3
courses changed
did not find matching config element, adding new config: 336551121
config limit changed
config unlimited changed
did not find existing matching scheduling subpart, created new one: Lec 
subpart minutes per week changed
added subpart credit
subpart credit changed
config subparts changed
BAND 201 Lec _ 'class' matching class not found adding new class
Not Loading 'offering' Error: null
<offering id="165165165" action="insert" offered="true"> <courseCredit fixedCredit="3" creditFormat="fixedUnit" creditUnitType="semesterHours" creditType="collegiate"/> <course id="100001090" title="PRIN. OF ACCOUNTING I " courseNbr="201" subject="BAND" scheduleBookNote="" controlling="true"> <consent type="NONE"/> </course> <config name="336551121" limit="35"> <subpart type="Lec" suffix="_" minPerWeek="50"> <subpartCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="3"/> </subpart> <class id="20009631" type="Lec" suffix="_" limit="35"> </class> </config> </offering>

**Comment by tomas-muller** [comment]
The error appears only in Unitime 4.2 (due to a recent change allowing an instructor to be assigned to a class multiple times when having different teaching responsibilities) and has been fixed in build 102.
