### ISSUE TITLE
Error while exporting an academic session

### ISSUE THREAD

**Issue by rafati** [UniTime/unitime#25]
I am getting the error below while exporting an academic session in Version 4.2.104 built on Sat, 25 Feb 2017.
The error can be replicated in https://demo.unitime.org
 
Unable to export: could not resolve property: null of: org.unitime.timetable.model.ExternalDepartmentStatusType [select distinct q235.null from org.unitime.timetable.model.Session q0, org.unitime.timetable.model.Department q7 inner join q7.externalStatusTypes q235 where q7.session = q0 and q0.uniqueId = :sessionId]

**Comment by tomas-muller** [comment]
The error appears only in Unitime 4.2 and it has been fixed in build 105.
