### ISSUE TITLE
Connecting an external Application, so that it generates the Schedule automatically.

### ISSUE THREAD

**Issue by TeddySipra** [UniTime/unitime#30]
Connecting an EXTERNAL APPLICATION to the UNITIME APIS, and indicate that UNITIME generates the schedule automatically.
Can you help me find a solution, thanks?

**Comment by tomas-muller** [comment]
Once you have a solution saved and committed, you can, for instance, use the Events API to retrieve all class events for the given term. Or you can export it in an XML format, using the Course Timetable or Course Offering (including course timetable) exports from the Data Exchange page.

Or, if you just want to export the solution as it is loaded/computed by the solver, you can export it directly from the Solver page in CSV format using the Export Solution button.

You can also export the committed solution using the Data Exchange API, for example:
http://demo.unitime.org/UniTime/api/exchange?term=Fal2010&type=timetable&token=1xhp5vo3zfxrpbzjzhtanmcipolx03fv42ohz4xa507x5acydh

**Comment by TeddySipra** [comment]
Good morning Tomas Muller, thank you very much.


Best Regards,

Teddy Sipra


________________________________
De: Tomáš Müller <notifications@github.com>
Enviado: martes, 23 de enero de 2018 05:39:51 a.m.
Para: UniTime/unitime
Cc: TeddySipra; Author
Asunto: Re: [UniTime/unitime] Connecting an external Application, so that it generates the Schedule automatically. (#30)


Once you have a solution saved and committed, you can, for instance, use the Events API to retrieve all class events for the given term. Or you can export it in an XML format, using the Course Timetable or Course Offering (including course timetable) exports from the Data Exchange page.

Or, if you just want to export the solution as it is loaded/computed by the solver, you can export it directly from the Solver page in CSV format using the Export Solution button.

You can also export the committed solution using the Data Exchange API, for example:
http://demo.unitime.org/UniTime/api/exchange?term=Fal2010&type=timetable&token=1xhp5vo3zfxrpbzjzhtanmcipolx03fv42ohz4xa507x5acydh
