### ISSUE TITLE
Error when add Configuration for Course

### ISSUE THREAD

**Issue by Eagle2411** [UniTime/unitime#34]
I tested Unitime on two version 4.2 and 4.3. Both version are occurred an error when i add or edit Configuration for Courses at Instructional Offering.
The error is : "Configuration could not be updated. If possible, split your configuration change into 2 or more separate operations."
I deployed Unitime on a computer with Window 10.
I tried to do the same on your online demo, it worked ok.

**Comment by tomas-muller** [comment]
Please provide more information so that I can reproduce the problem. Is there any error in the Tomcat log?

**Comment by Eagle2411** [comment]
hi  Tomáš Müller,
I deployed Uni Time (version 4.3) on Window server 2012 with Tomcat 8.5.
At "Instructional Offerings"  page, I added new course "ALG 100", and then
I add new Configuration for this Course. But when i pressed "save" button,
I got an Error " *Configuration could not be updated. If possible, split
your configuration change into 2 or more separate operations* ". I didn't
change anything else.
Please guide me how to solve this problem. I attached the log Tomcat file
with this mail.

best regards,
Quang Ninh, LE

**Comment by tomas-muller** [comment]
Are you using MySQL 8?

Please note that UniTime does not support MySQL 8 yet. It should work fine with MySQL 5.5, 5.6, or 5.7.
