### ISSUE TITLE
Building and Rooms XML

### ISSUE THREAD

**Issue by olgunozoktas** [UniTime/unitime#39]
I have tried the example XML for buildings and rooms which is in this link https://www.unitime.org/interface/buildingRoomImport.xml but unfortunately i couldn't succeed. Are there any other way to do it?

**Comment by tomas-muller** [comment]
What do you mean by "i couldn't succeed". Was there an error? If so, please provide more details.

Please note that for rooms to be visible in UniTime, you need to go to Administration -> Academic Sessions -> Buildings and in the Buildings screen click on Update Data after the import. The reason for this is that we have two sets of rooms, the list of external rooms (which are imported from the XML, and expected to be changed quite often), and the list of rooms that are actually being used for timetabling -- that should not change uncontrollably especially during the time a course timetable is being produced.

**Comment by olgunozoktas** [comment]
Thank you very much its works now, i didn't know that i should click Update Data after the import,
