### ISSUE TITLE
Error in Date patterns after modify the Academic session dates

### ISSUE THREAD

**Issue by nuria2c** [UniTime/unitime#4]
When you have defined an Academic Session an a Date Pattern and modify the start date of the session, automatically modify the date patterns class days.
Example
1. Create a session that starts on Monday September 7, 2015
2. Create a Date pattern and select the class days (weekly from Monday to Friday - 5 consecutive days)
3. Change the start date of the session to Tuesday 1 stiembre 2015
4. The Date patterns created modify the class days from Tuesday to Saturday (5 days consecutive but displaced from Tuesday).

**Comment by tomas-muller** [comment]
This is not a bug. The date patterns are intentionally made relative to the academic session begin date (a date pattern is stored as a bit map (1 or 0 for each day) and an offset between the academic session start and the first day of the bit map). This makes the date patterns very easy to move between academic sessions.

Similarly, examination periods are relative to the examination begin date that is set on the academic session too.
