### ISSUE TITLE
How to add datepattern and time preference to the class offerings in xml?

### ISSUE THREAD

**Issue by olgunozoktas** [UniTime/unitime#41]
By using XML how can i add datepattern and timepreference to the offerings?

**Comment by tomas-muller** [comment]
Time and date pattern can be imported with the time assignment using the Courses XML or Timetable XML format (e.g., see https://www.unitime.org/interface/courseTimetableImport.xml).

Preferences (including time preferences) can be also imported using the Preferences XML. See https://www.unitime.org/interface/preferences.xml for an example.

We currently do not have an XML import that would only assign date patterns to scheduling subparts and/or classes.

For questions of this nature, please use support@unitime.org email or the [unitime-discuss](https://groups.google.com/forum/#!forum/unitime-discuss) Google Group.

**Comment by olgunozoktas** [comment]
Thank you very much sir
