### ISSUE TITLE
admin  admin is not recognized

### ISSUE THREAD

**Issue by karammr** [UniTime/unitime#46]
I followed the steps verbatim 
i entered admin admin for username and password respectively
it failed to log me in
what am i doing wrong?

Thanks

**Comment by tomas-muller** [comment]
It is hard to say as you have not provided any details.

Was there any error on the login screen? Are there any errors in the tomcat log?

**Comment by karammr** [comment]
Thank you for your prompt response
The error on the log in screen was: Authentication failed: Login Failure:
all modules ignored.
The log is:


ERROR  TableGenerator -> could not read a hi value - you need to populate
the table: timetable.hibernate_unique_key
[01/24/19 21:25:17] ERROR  QueryLogFilter -> Failed to persist 1 log
entries:could not read a hi value - you need to populate the table:
timetable.hibernate_unique_key
org.hibernate.id.IdentifierGenerationException: could not read a hi value -
you need to populate the table: timetable.hibernate_unique_key
at org.hibernate.id.TableGenerator$1.execute(TableGenerator.java:169)
at org.hibernate.id.TableGenerator$1.execute(TableGenerator.java:154)
at
org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:72)
at
org.hibernate.jdbc.AbstractReturningWork.accept(AbstractReturningWork.java:51)
at
org.hibernate.engine.transaction.internal.jdbc.JdbcIsolationDelegate.delegateWork(JdbcIsolationDelegate.java:74)
at org.hibernate.id.TableGenerator.generateHolder(TableGenerator.java:153)
at
org.hibernate.id.TableHiLoGenerator$1.getNextValue(TableHiLoGenerator.java:90)
at
org.hibernate.id.enhanced.LegacyHiLoAlgorithmOptimizer.generate(LegacyHiLoAlgorithmOptimizer.java:77)
at org.hibernate.id.TableHiLoGenerator.generate(TableHiLoGenerator.java:87)
at
org.unitime.commons.hibernate.id.UniqueIdGenerator.generate(UniqueIdGenerator.java:65)
at
org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:118)
at
org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:209)
at
org.hibernate.event.internal.DefaultSaveEventListener.saveWithGeneratedOrRequestedId(DefaultSaveEventListener.java:55)
at
org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:194)
at
org.hibernate.event.internal.DefaultSaveEventListener.performSaveOrUpdate(DefaultSaveEventListener.java:49)
at
org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:715)
at org.hibernate.internal.SessionImpl.save(SessionImpl.java:707)
at org.hibernate.internal.SessionImpl.save(SessionImpl.java:702)
at
org.unitime.timetable.filter.QueryLogFilter$Saver.run(QueryLogFilter.java:255)




*Kindest Regard*
_________________________________________________
*Marcel *
_________________________________________________

**Comment by karammr** [comment]
Thank you so much
I was able to enter
- Instructors
- Rooms
- classes

I have couple questions if you don't mind:
With respect to removing the subjects for the Instructional planning
department,how can I do that?
How can I create a timetable? or delete one?

Thank you and Thank you
Marcel
*Kindest Regard*
_______________________________________________________
*Marcel R. Karam, *
*                              https://www.linkedin.com/in/marcelkaram/
<https://www.linkedin.com/in/marcelkaram/>*
_______________________________________________________

**Comment by tomas-muller** [comment]
You can delete a subject area (or move it under a different department) on the [Edit Subject Area](http://help.unitime.org/Edit_Subject_Area) page, but only when there are no offered courses in the subject area.

You can create a timetable using the Course Timetabling > [Solver](http://help.unitime.org/Course_Timetabling_Solver) page. You can delete a saved timetable on the Course Timetabling > [Saved Timetables](http://help.unitime.org/Timetables) page.

For more details, please see the following manuals:
- [Administrative User Manual](https://docs.google.com/document/d/1iuj9NwrqkiVeJvKn1Sd41qqaVEJGwO79y1KZo1mtwuw)
- [Course Timetabling Data Entry Manual](https://docs.google.com/document/d/1rjS_6ebwegSTcN5Iw57qui5CHG8_6TWnk8MCwBwAt58)
- [Course Timetabling Solver Manual](https://docs.google.com/document/d/1NZmKnmrjM2Tqg7dO18cWcMIe_GrtilQtKw6d1WGWBtY)

These manuals are also available in the menu, under Help > Manuals.

You can also take a look at our [Course Timetabling in UniTime](https://youtu.be/k3FAhKa3HOA) webinar recording.
