### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by dhensche** [UniTime/unitime#47]
If this is really an open source project, are their any development guidelines or instructions on how to get started with development/contributing? I don't see a basic "how to build" section in the README, is this buried somewhere else in the project or project website?

**Comment by tomas-muller** [comment]
For instructions on how to build UniTime, please see http://help.unitime.org/build

There are also instructions on how setup UniTime in Eclipse, see http://help.unitime.org/eclipse for more details.

**Comment by dhensche** [comment]
Thank you @tomas-muller , I wasn't able to find that page for some reason
