### ISSUE TITLE
Can not login on a fresh installation

### ISSUE THREAD

**Issue by mabsalhi** [UniTime/unitime#51]
Salam,
I have achived a fresh unitime installation for testing and discovering the application functionalities, but once i'v deployed my application i would not log inside.
I have deployed unitime 4.4 build130.
My server is a tomcat 8 runing on a Zulu Jdk 8, with mariadb database and mysqlJ everything well setted.

when i try to log in using username and password : admin/admin or anything else(curicculum, exam, event) it does not work, and i do not receive any error message on the login page.

i have regenerated the password using : 
java -cp unitime/solver/timetable.jar org.unitime.timetable.authenticate.jaas.DbAuthenticateModule admin
ISMvKXpXpadDiUoOSoAfww==
And iserted it in my users table.
the image attached bellow show the catalina.log properties who not report any authentication error, same as the login page.
![loginUnitimeNoError](https://user-images.githubusercontent.com/2107179/66469109-31471900-ea7f-11e9-961e-bcf7a7cb8426.png)

![catalinaOut](https://user-images.githubusercontent.com/2107179/66469092-25f3ed80-ea7f-11e9-8d13-ae3fa8a8b822.png)

Please if some one have faced the same issue, i will be thankful to have some advise.

Thanks.

**Comment by tomas-muller** [comment]
Usually, when the login fails, there is the following message:

> Authentication failed: Login Failure: all modules ignored.

Have you made any changes to the spring security configuration?

Are there any errors in the tomcat log? Or were there during the first deployment of UniTime (when it does all the database updates)? The message from the DefaultSecuritySpringContextSource only means that you do not have LDAP authentication configured.

Do you have any academic session created? There always needs to be at least one academic session for UniTime to work properly. You can check that by looking at the sessions table -- it should not be empty.

```
mysql> select academic_year, academic_term, academic_initiative from sessions;
+---------------+---------------+---------------------+
| academic_year | academic_term | academic_initiative |
+---------------+---------------+---------------------+
| 2007          | Fal           | woebegon            |
| 2010          | Fal           | woebegon            |
+---------------+---------------+---------------------+
2 rows in set (0.00 sec)
```

Please note that at least one academic session is created during the installation (either using blank-data.sql or woebegon-data.sql) and the UniTime user interface does not allow the user to delete the active (currently used) academic session, so there is always at least one.
