### ISSUE TITLE
Error: Failed to load timetables: null

### ISSUE THREAD

**Issue by Therzidij** [UniTime/unitime#54]
When I try to view the **Timetable Grid** I get the message: **Failed to load timetables:null.**  Although the **Solver log** does not show an error and I can export the table from the **Saved Timetables** to Excel. What could be reason?

**Comment by tomas-muller** [comment]
The problem likely is that you do NOT have a default date pattern defined. It is needed to populate the available weeks in the Filter.

You need to have at least one date pattern defined on the Administration > Academic Session > Date Patterns page. You also need to mark one of them as default (typically the one that spans all the weeks during which classes take place). You can do that on the Edit Date Pattern page or on the Edit Academic Session page. It is also used for all classes that do not have a date pattern selected on the class or on the scheduling subpart.

If this is not the case, please check the tomcat log for more details about the error.

**Comment by Therzidij** [comment]
Thank you very much!!!
