### ISSUE TITLE
Error: Solver -> Load -> FATAL: Unable to load input data, reason: unexpected token: 0 near line 1

### ISSUE THREAD

**Issue by Therzidij** [UniTime/unitime#55]
When I try Load in Solver I get Error. What could be reason?

FATAL: Unable to load input data, reason: unexpected token: 0 near line 1, column 213 [select distinct i.externalUniqueId, a from org.unitime.timetable.model.ClassInstructor ci inner join ci.instructor i inner join ci.classInstructing.assignments a where ci.lead = true and i.externalUniqueId in (''08','19','18','17','16','15','14','11','19','10','18','17','16','15','10','14','11','06','09','08','08','07','06','09','05',''08','04','07','03','02','05','01','04','03','02','01') and a.solution.owner.session.uniqueId=:sessionId and a.solution.commited=true and a.solution.owner.uniqueId not in (5308416)] <<<

**Comment by tomas-muller** [comment]
Looks like you have an instructor with an apostrophe in the external unique id: '08. Is that intentional?

Also, please note that the instructor external unique ids are expected to be unique.

**Comment by Therzidij** [comment]
Thank you very much!
