### ISSUE TITLE
Division into groups

### ISSUE THREAD

**Issue by Therzidij** [UniTime/unitime#56]
Where in the UniTime is the division into groups? For Example : We have two groups in Preparatory Program: Group_1 and Group_2. Where can we add them to UnitTime to see in the schedule separately by groups?

**Comment by tomas-muller** [comment]
By default, UniTime schedules individual students and minimizes conflicts between classes they take by
 - moving a student between alternative classes
 - placing a class in a different time (and room in case of distance conflicts)

It takes student course demands (which could be in a form of last-years student course enrollments, curricula, the actual pre-registrations, or a combination of these), see the Student Course Demand parameter of the [Solver](http://help.unitime.org/Solver) for more details about these options.

That said, it is possible to fix certain students to a particular class by using reservations. For instance, there can be a different classification for each group (e.g., G1 and G2) and Lecture 1 of a course is reserved to students of G1 (of a particular curriculum) and Lecture 2 for students of the second group G2.
