### ISSUE TITLE
University Schedule Logic

### ISSUE THREAD

**Issue by Therzidij** [UniTime/unitime#57]
Could you please help with our logic of scheduling of the courses.
We divided students by  groups (Preparatory year is divided like two different groups 21 students are in one group A and 21 students in second group B). We need to schedule the courses by groups and then the system should show it in one line for group A and in second line group B. In an attached file I have example of the schedule which we want to have . Please guide how can we manage it.

![Schedule](https://user-images.githubusercontent.com/57082470/70019962-5787c180-15b5-11ea-89d8-3797664b27c7.jpg)

**Comment by tomas-muller** [comment]
As mentioned in issue #56, you can split the first year classification into two, e.g., 1A and 1B and configure the curriculum with 21 students in each of the two classifications. This will allow you to see the schedule individually for each curriculum and classification in the grid.

If you need to ensure that, for instance, students of 1A classification/group will take Lec 1 and students of 1B will take Lec 2, you will need to set up curriculum reservations (reserving all space in Lec 1 to 1A students and all space in Lec 2 to 1B students).
