### ISSUE TITLE
why i can not find Instructor Scheduling Solver Page on the nav page 

### ISSUE THREAD

**Issue by imanman** [UniTime/unitime#58]
when i set up unitime 4.4 ,running on my laptop ,but i find i  can not find Instructor Scheduling Solver page and i can not find teaching request create and manage page .....
i login in by admin/admin .

any idea ?  i am a new to unitime , looking forward to reply， thanks a lot!

**Comment by tomas-muller** [comment]
There needs to be at least one instructor available for instructor scheduling solver to become available (you need to set up your instructors first). This can be done on the Instructors page, click on an instructor, click Edit Assignment Preferences and put in maximal teaching load and set the teaching preference to something else than prohibited. This will also enable the Setup Teaching Requests button/page from the Instructional Offering Detail page.

For more details, please see the Instructor scheduling manual ([bit.ly/unitime-instructor-scheduling](http://bit.ly/unitime-instructor-scheduling), also available in UniTime under Help > Manuals).

**Comment by imanman** [comment]
@tomas-muller thanks a lot。
