### ISSUE TITLE
UniTime Localization 

### ISSUE THREAD

**Issue by mohammed3azzam** [UniTime/unitime#63]
Please How can I make localization for Unitime

**Comment by tomas-muller** [comment]
Please see [http://help.unitime.org/Localization](http://help.unitime.org/Localization) for more details about localization.  If you wish to provide translations using Zanata, just send your Zanata user name and the language you wish to work on to support@unitime.org and we will give you access to the UniTime project in there ([https://translate.zanata.org/project/view/unitime](https://translate.zanata.org/project/view/unitime)).
