### ISSUE TITLE
Error when Import XML file

### ISSUE THREAD

**Issue by Moh3Azzam** [UniTime/unitime#64]
i got this error Exception: Academic session id not provided when trying to import XML file 
![2020-07-19_14-40](https://user-images.githubusercontent.com/37277171/87874919-ed9a1c00-c9cd-11ea-94d1-76a698ca9191.png)

**Comment by tomas-muller** [comment]
The pu-spr07-cs.xml downloaded from [University Course Timetabling Benchmark Datasets](https://www.unitime.org/uct_datasets.php) cannot be imported into UniTime. It just contains information needed by the course timetabling solver to solve the problem in an anonymized form. The solver XML format is described at [https://www.unitime.org/uct_dataformat_v24.php](https://www.unitime.org/uct_dataformat_v24.php) and the execution of the CPSolver using this XML is described at [https://www.unitime.org/uct_execution.php](https://www.unitime.org/uct_execution.php).

XML formats that can be imported into UniTime using the [Data Exchange](http://help.unitime.org/Data_Exchange) page are described on [https://www.unitime.org/uct_interfaces.php](https://www.unitime.org/uct_interfaces.php).

**Comment by Moh3Azzam** [comment]
Thanks but how i can add student for current session

**Comment by tomas-muller** [comment]
Students cannot be created directly in UniTime. We expect students to be imported into UniTime from a Student Information System. It is possible to import a student using our XML interface (see [http://www.unitime.org/uct_interfaces.php](http://www.unitime.org/uct_interfaces.php), in particular the [Students XML](https://www.unitime.org/interface/studentInfoImport.xml) or the [Student course requests XML](https://www.unitime.org/interface/woebegonStudents.xml) format).

**Comment by Moh3Azzam** [comment]
We are new and we are trying to demonstrate unitime functionality do u have a sample data that contains 
- students information
- courses
- rooms
to generate a sample time table for a small college and in the demo to my team
appreciate your help

**Comment by Moh3Azzam** [comment]
Thank you for the prompt response 
I want to edit the student course request can you help me how I can
![2020-07-21_11-56](https://user-images.githubusercontent.com/37277171/88040961-fadc1580-cb49-11ea-87f7-0d9ab5f56c2f.png)

**Comment by tomas-muller** [comment]
You will need to drop the existing class enrollments first (the Student Course Request page/dialog does not allow a student to remove courses that he/she is already enrolled in). You can do that using the Students > Batch Solver page:
1. open the page, hit Load, wait for Awaiting Commands...
2. hit Refresh and then Clear, confirm the choice
3. hit Save, confirm the choice, wait for Awaiting Commands...
4. hit Unload

**Comment by Moh3Azzam** [comment]
I did the past instruction but I can't make submit button and I can't change the default
![2020-07-21_16-34](https://user-images.githubusercontent.com/37277171/88068173-24a83300-cb70-11ea-8f7d-d942f2582a58.png)

**Comment by tomas-muller** [comment]
So, do you have the student set to the system default / All Enabled status? Looks like all (or at least those that are below the Set student status.. dialog) students are in the Disabled status.

The ability to use the Course Requests page is given by the 4 checks in the Permissions table in the Student Course Requests line. For the admin to make changes you need the Changed Admin check (last one).

The Special Registration is something different -- it is a 3rd party integration allowing to check for registration errors and request overrides.

You can define the student statuses on the Administration > Other > Student Status Types page.

**Comment by Moh3Azzam** [comment]
Thanks but there is any steps guide?

**Comment by Moh3Azzam** [comment]
sorry but i still have the same problem I can't submit the submit requests is disabled

**Comment by Moh3Azzam** [comment]
and when i tried to enter Course Requests I got this message
![2020-07-22_13-30](https://user-images.githubusercontent.com/37277171/88172579-81aff180-cc21-11ea-8f8f-3bc1dcdeff7f.png)

**Comment by tomas-muller** [comment]
To be able to use the Course Requests page, the academic session status (that is set on the Administration > Academic Sessions > Academic Sessions page) must be set to a status that allows for Student Sectioning Registration. By default, only the Demo (All Enabled) status has this set -- see Administration > Other > Status Types for the available statuses and their parameters.

Besides the session status, the student status must allow for Registration and Student Register, Advisor Register, or Admin Register depending on the role of the user using the Student Course Requests page. See Administration > Other > Student Status Types for the existing student statuses. The default student status can be set on the academic session (same place as the session status) and it can be changed on individual students using the Online Student Scheduling Dashboard.

All the available UniTime documentation is listed on the [http://bit.ly/unitime44docs](http://bit.ly/unitime44docs) page.

**Comment by Moh3Azzam** [comment]
Thank u very much
I want to ask about the solve It takes approximately 30 min for demo data is there a way to minimize this time take?

**Comment by tomas-muller** [comment]
Due to the stochastic nature of the search algorithm, it is not guaranteed that it will find an optimal solution. Also, the solver keeps on running and trying to find an improvement until the time runs out. Usually, you can see that the solution stops improving or gets it gets improved very slowly after some time. The solver can be stopped after that.

You can change the default solver time limit and a lot of other properties in the solver configuration, Administration > Solver > [Configurations](http://help.unitime.org/Solver_Configurations) page. Look for "Maximal solver time (in sec)".

**Comment by Moh3Azzam** [comment]
Thanks a lot but in Student Scheduling Assistant when I want to change like in the **image(1)** after I select the button submit not appear to save my new alternative but in the demo version, I can submit my change
there is any configuration that make this button appear?
**image(1)**
![2020-07-26_15-57](https://user-images.githubusercontent.com/37277171/88480986-73334400-cf59-11ea-9ed9-99779de3a648.png)


here is my configuration in Status type
![2020-07-26 16 04 25 0 0 0 0](https://user-images.githubusercontent.com/37277171/88481108-d9b86200-cf59-11ea-86c3-c3d9e2f5a7a5.png)

**Comment by tomas-muller** [comment]
On the status type, you need to have the "Online Sectioning" toggle in the Student Sectioning section checked.

**Comment by Moh3Azzam** [comment]
I toggle the checkbox for "Online Sectioning" but I have the same problem
![2020-07-27 10 23 29 0 0 0 0](https://user-images.githubusercontent.com/37277171/88520020-4cc1e700-cff3-11ea-9717-ad1d7856b264.png)
![2020-07-27 10 23 44 0 0 0 0](https://user-images.githubusercontent.com/37277171/88520022-4df31400-cff3-11ea-8a0b-33f94eca0083.png)


but the demo version the button submit Schedule appears
![2020-07-27 10 25 26 demo unitime org](https://user-images.githubusercontent.com/37277171/88520172-7f6bdf80-cff3-11ea-9ffe-4be47f3e5301.png)

**Comment by tomas-muller** [comment]
You probably need to update the academic session (on Administration > Academic Sessions > Academic Sessions, click on the academic session, and hit Update) for the online scheduling server to notice the status change.

If that does not help, go to Administration > Solver > Manage Solver, and click Reload on the Fal 2010 online scheduling server (Manage Online Scheduling Servers table).

**Comment by Moh3Azzam** [comment]
thanks and I'm sorry for bothering you is there a way to reset the default configuration?
and if I want student to log in and modify his schedule what is the default username and password?

**Comment by tomas-muller** [comment]
There is only one student log in in the demo (Student Brian with ext id 1002), with the student as the username as well as password. You can define more on the Administration > Other > Users page (the external id of the student must match the external id on this page). In the demo, students have external ids between 1001 and 1019.

What do you mean by resetting the default configuration? You can reset your unitime database back to what it was after a fresh installation by:
1. stop the tomcat
2. run the schema.sql and woebegon-data.sql MySQL scripts (to re-create the database and populate it with the demo content)
`mysql -uroot -p <schema.sql`
`mysql -utimetable -punitime timetable <woebegon-data.sql`
3. start the tomcat again

**Comment by Moh3Azzam** [comment]
i mean back to the default configuration like Administration > Other > Status Type

**Comment by Moh3Azzam** [comment]
Thanks all thing work fine now
