### ISSUE TITLE
Combining distribution preferences

### ISSUE THREAD

**Issue by hasnul** [UniTime/unitime#65]
Is it possible to have a distribution preference of either 'Back-To-Back on the same day' OR 'Different Days'?

**Comment by tomas-muller** [comment]
You can use the Max Break constraint for that (see [Additional Distribution Constraints](http://help.unitime.org/Additional_Distribution_Constraints) for more details). Please note that these additional distribution constraints are not available in UniTime by default, they need to be registered first. For the No Break constraint (max break with zero breaks), you need to download the [Create Max Break Constraint.xml](https://raw.githubusercontent.com/UniTime/unitime/master/Documentation/Scripts/Create%20Max%20Break%20Constraint.xml) script, import it using the Administration > Academic Sessions > Data Exchange page and then on the Administration > Utilities > Scripts run the imported script Distribution Types: Create Max Break Constraint with the appropriate parameters.
