### ISSUE TITLE
Course Offering Import and other import's issues

### ISSUE THREAD

**Issue by ebracci** [UniTime/unitime#70]
I'm new with unitime and I'm using the page https://www.unitime.org/uct_interfaces.php to create the xml to import some data for testing.

Unfortunately, I'm having some issues, which i'd like to resolve:

1) When trying to import some courses, the number of rooms is always 0 and the only way to change it is through using the form of class configuration. How can I set the default number of Rooms to 1, without having to change it manually every time?

2) When creating the staff.xml to import instructors, is it normal not to see them automatically in the assigned department? 

3) In the preferences.xml, is groupPreferences the name of the Room group that I have previously  created?

Thank you for your support

**Comment by tomas-muller** [comment]
1. When trying to import some courses, the number of rooms is always 0 and the only way to change it is through using the form of class configuration. How can I set the default number of Rooms to 1, without having to change it manually every time?

The number of rooms defaults to 1 unless you are importing the assignments as well (there is a `time` element inside of the `class` element). If there is `time`, it is expected that there will be rooms as well (`room` or `location` elements), and the number of rooms is set to the number of `room` and `location` elements listed under the `class` element.

If no assignment is imported, you can use `nbrRooms` attribute on the `class` element to set the number of rooms to a different number than one.

If you are uncertain how to model a certain course structure, you can set it up manually in UniTime and use the Data Exchange page to export Course Offerings to get an example XML.

2. When creating the staff.xml to import instructors, is it normal not to see them automatically in the assigned department?

Staff XML is imported into the staff table, to pull in the instructors you need to use the Manage Instructor List operation on the Instructors page (menu Courses > Input Data > Instructors).

3. In the preferences.xml, is groupPreferences the name of the Room group that I have previously created?

The room group abbreviation is used.
