### ISSUE TITLE
Courses Timetabling missing under the Courses menu

### ISSUE THREAD

**Issue by tsnouidui** [UniTime/unitime#71]
I have installed unitime on my Windows 10 machine. I have created a new session and logged in as an admin. Unfortunately I cannot see the _Courses Timetabling_ under the _Courses_ menu and can therefore not run the Courses timetabling solver. I can only see _Input Data_ and _Reports_? What am I missing?

**Comment by tomas-muller** [comment]
Do you have any solver groups defined (see Administration > Academic Sessions > Solver Groups)? Solver groups define which departments are to be timetabled together.

For more details, please take a look at the administration and course timetabling manuals under the Help > Manuals menu. You can also take a look at the Course Timetabling with UniTime webinar at [https://youtu.be/k3FAhKa3HOA](https://youtu.be/k3FAhKa3HOA).
