### ISSUE TITLE
Can't roll instructors forward

### ISSUE THREAD

**Issue by tsnouidui** [UniTime/unitime#74]
I have one session with a number of instructors that I need to roll forward along with other information to a newly created session. I can successfully roll information such as subject areas but I don't seem to be able to roll the instructors list forward. I have selected them but failed to have them roll over. Anything I need to pay attention to?
By the way, I am not sure whether GitHub is the best place to post such kind of questions, maybe a google group or something similar might be more appropriate?

**Comment by tomas-muller** [comment]
To be able to roll instructors forward, you need to roll the departments first. Once the departments are rolled forward, you can roll the instructors by checking the "Roll Instructor Data Forward From Session" toggle and selecting the departments for which the instructors are to be rolled forward in the "For Departments" list box (you can select all the departments -- most browsers have Ctrl+A shortcut for that).

By the way, you can also send questions directly to [support@unitime.org](mailto:support@unitime.org) or using the [unitime-discuss](https://groups.google.com/g/unitime-discuss) Google group.

**Comment by tsnouidui** [comment]
I have tried with no luck. I can see the department in the new session. I can see the option to roll forward instructors from that department but when I do it I just get an empty list of instructors

**Comment by tomas-muller** [comment]
I do not know -- this usually works as expected. I would need to see the data to see what is going wrong?

Is there any error? On the roll forward page or in Tomcat's log?
