### ISSUE TITLE
Delay in updating list of subject areas

### ISSUE THREAD

**Issue by tsnouidui** [UniTime/unitime#76]
When I add a new subject area under "Subject Areas" of an academic session, it takes a long time (more than 15mins) before it gets reflected in the Instructional Offering list options. Is there anything that can be done so the entry gets updated faster?

**Comment by tomas-muller** [comment]
I am not able to reproduce this issue. However, you can try Administration > Utilities > Clear Cache to clear the cached data.

**Comment by tsnouidui** [comment]
Administration > Utilities > Clear helps. Thanks a lot
