### ISSUE TITLE
Reservations student groups time between Courses 

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [UniTime/unitime#79]
How to change time between Course at less  30 min to 90 min  (not 225 min )
![Reservations student groups](https://user-images.githubusercontent.com/46826627/112073030-3a994800-8b84-11eb-8281-ddfd6d089d63.PNG)

**Comment by tomas-muller** [comment]
By default, UniTime does not minimize breaks between classes for students. It only minimizes the number of student conflicts, that is cases, where a student has two classes that are overlapping in time or that are back-to-back in rooms that are too far apart.

However, there is the [StudentMinimizeScheduleHoles](https://github.com/UniTime/cpsolver/blob/master/src/org/cpsolver/coursett/criteria/additional/StudentMinimizeScheduleHoles.java) additional criterion that can be enabled. It will make student schedules more compact, but possibly also more spread across the week. This criterion is not enabled by default but can be enabled by setting the General.AdditionalCriteria solver parameter (Administration > Solver > Parameters page). It is a semicolon-separated list of classes to be included.

![image (1)](https://user-images.githubusercontent.com/10631634/112215078-3ae72100-8c20-11eb-8a55-f4ca8a09e4de.png)

When enabled, you should see the "Average class distance" in the solution info (Solver page). It is the average time between any two classes that a student has on the same day (the solver tries to minimize this number).

**Comment by Abdulaziz-KTA** [comment]
thank you

**Comment by Abdulaziz-KTA** [comment]
what you mean that ???????? --> It is a semicolon-separated list of classes to be included.

**Comment by tomas-muller** [comment]
The additional criteria parameter allows to plug in additional optimization criteria that are not part of the original model. The parameter contains a list of Java classes that extends the [TimetablingCriterion](https://github.com/UniTime/cpsolver/blob/master/src/org/cpsolver/coursett/criteria/TimetablingCriterion.java) class. If there are two or more, these are separated by a semicolon. For example:

org.cpsolver.coursett.criteria.additional.ImportantStudentConflict;org.cpsolver.coursett.criteria.additional.StudentMinimizeScheduleHoles

This will tell the solver to include [ImportantStudentConflict](https://github.com/UniTime/cpsolver/blob/master/src/org/cpsolver/coursett/criteria/additional/ImportantStudentConflict.java) criterion (student conflicts that are marked as important can be weighted more) and [StudentMinimizeScheduleHoles](https://github.com/UniTime/cpsolver/blob/master/src/org/cpsolver/coursett/criteria/additional/StudentMinimizeScheduleHoles.java) (minimizing holes in student schedule).

**Comment by Abdulaziz-KTA** [comment]
thank you 
the first question I got it 
the second one where I find ("Average class distance" in the solution info (Solver page)) Can you share it as an image? plz

**Comment by tomas-muller** [comment]
The field is called "Student class distance" and it shows at the bottom of Current Timetable as well as Best Timetable section. This is on the Courses > Course Timetabling > Solver page.

<img width="888" alt="Screen Shot 2021-03-24 at 21 32 41" src="https://user-images.githubusercontent.com/10631634/112379561-9381f100-8ce8-11eb-9471-3562ea89e14d.png">

**Comment by Abdulaziz-KTA** [comment]
oh thank you
