### ISSUE TITLE
Translate into Arabic

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [UniTime/unitime#81]
How do I translate the system into Arabic?

**Comment by tomas-muller** [comment]
Please take a look at [http://help.unitime.org/Localization](http://help.unitime.org/Localization). If you wish to provide Arabic translations using Zanata, just send me your Zanata user name and I will give you access to the UniTime project there ([https://translate.zanata.org/iteration/view/unitime/4.5](https://translate.zanata.org/iteration/view/unitime/4.5)).

**Comment by Abdulaziz-KTA** [comment]
Zanata user name : aktharbi

**Comment by tomas-muller** [comment]
I have just added you to the UniTime project on Zanata with permission to provide and review Arabic translations.

**Comment by Abdulaziz-KTA** [comment]
Thank you, I will do my best.

**Comment by Abdulaziz-KTA** [comment]
![image](https://user-images.githubusercontent.com/46826627/142752657-7483fdee-4881-4037-8080-88dc76fd96f0.png)

Where can I find these words in zanata?

**Comment by tomas-muller** [comment]
Unfortunately, some of the older pages are not made localizable yet (mostly pages that are used by administrators written using JSP and Struts). This includes the Add/Edit Academic Session page.

While we would like to have the whole application localized, it does not have a high priority on our to-do list. We welcome any help we can get in this regard.

**Comment by Abdulaziz-KTA** [comment]
what can I help that?

**Comment by tomas-muller** [comment]
At the moment, older pages have the messages hard-coded in the JSPs and the Java code (e.g., see [sessionEdit.jsp](https://github.com/UniTime/unitime/blob/master/WebContent/admin/sessionEdit.jsp#L126-L145) for the Add/Edit Academic Session JSP). To make these pages localizable, these hard-coded messages need to be taken out using a Message interface like it is explained in the [Localization](https://help.unitime.org/localization) document. See commit ffb47dd for an example (localization of the Instructors page). As you can see, it is a lot of tedious work.

Also, we are gradually moving away from JSP/Struts and all the new pages are written using GWT and in a way that they are already internationalized. We also plan to rewrite the old pages using GWT (which has been already done for events, rooms, and course timetabling solver), but that is even more work and given its current priority will take a lot of time to complete.
