### ISSUE TITLE
zanata 

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [UniTime/unitime#82]
in (http://help.unitime.org/Localization)
Pull the translation from the project (e.g., by calling zanata-cli pull in your local UniTime repository). This should download the translation files under Documentation/Translations.
or using Maven (zanata:pull task)
and do all instructions create zanata.ini, download zanata.xml
can you show me how do that? plz. 
last one I use windows 10 and tomcat 8

**Comment by tomas-muller** [comment]
1) Clone UniTime repository

```
git clone https://github.com/UniTime/unitime.git
```

2) Download and install Arabic translations (using Apache [Maven](https://maven.apache.org/) and Apache [Ant](https://ant.apache.org/))

```
cd unitime
mkdir Documentation/Translations
mvn zanata:pull -Dzanata.locales=ar
ant import-translations -Dlocale=ar
```

3) Build unitime (using Apache [Ant](https://ant.apache.org/))

```
ant build
```

The resultant UniTime.war and timetable.jar files are located in the Distributions folder.

See for more details about how [http://help.unitime.org/build](http://help.unitime.org/build) on how to make a UniTime build.

Once you have the new UniTime.war deployed, you can open UniTime in Arabic using [http://localhost:8080/UniTime/login.do?locale=ar](http://localhost:8080/UniTime/login.do?locale=ar).

Please note that the Arabic locale has the basic right-to-left support enabled that has been experimentally added in UniTime 4.5 (not all the components support the right-to-left layout yet).

**Comment by Abdulaziz-KTA** [comment]
Is there a way to import a complete offline translation to Zenata translate???

**Comment by tomas-muller** [comment]
I think so, but I have never used the .po files (I have only used the web interface to put in translations). It is certainly possible to upload the translations from the .properties files using the Zanata client ([zanata-cli push](http://docs.zanata.org/en/latest/client/commands/push/)) or Zanata's maven plug-in ([mvn zanata:push](http://docs.zanata.org/en/latest/client/maven-plugin/commands/)).
