### ISSUE TITLE
Personal Schedule

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [UniTime/unitime#85]
any way to show only schedule to another website or mobile app????

**Comment by tomas-muller** [comment]
It is possible to use UniTime API (see [http://bit.ly/unitime44api](http://bit.ly/unitime44api)) to get a schedule of a person (e.g., see the Events API). If you need just iCAL or CSV file with the schedule, you can also use the Events exports (see [http://bit.ly/unitime44exports](http://bit.ly/unitime44exports)).

**Comment by Abdulaziz-KTA** [comment]
thank you

**Comment by Abdulaziz-KTA** [comment]
sorry can you explain, how to get timetables from UniTime to university website use Api???


![image](https://user-images.githubusercontent.com/46826627/120986078-e403d900-c784-11eb-8e73-37b7c3cf22c1.png)

**Comment by tomas-muller** [comment]
Well, once the course timetabling is done, the course timetable is usually exported to the Student Information System either using our XML, a custom script, or an existing integration (which we have with [Ellucian Banner and Colleague](https://github.com/UniTime/unitime-addons)). Or the students are given access to UniTime -- for instance, see the online demo which is configured to display class and examination schedules without authentication (see this [link](https://demo.unitime.org/UniTime/gwt.jsp?page=timetable&menu=false#events=&name=A%252FM1+01&term=Fal2010woebegon&type=curriculum) for a schedule of a particular curriculum; to see personal schedules students and instructors still need to authenticate). Alternatively, you can use the earlier mentioned UniTime APIs to build your own web application.

**Comment by Abdulaziz-KTA** [comment]
Sorry, I tried to understand but didn't know how or what I need to do.
Can you explain or any video or presentation explain that and sorrry.

**Comment by tomas-muller** [comment]
Can you just link UniTime from the university website? For example, using [https://demo.unitime.org/UniTime/gwt.jsp?page=classes](https://demo.unitime.org/UniTime/gwt.jsp?page=classes) for a schedule of classes.

It is not possible to display a UniTime page within an iframe or something like that without making any substantial configuration changes, mostly due to the cross-site scripting and similar restrictions in modern browsers.

**Comment by Abdulaziz-KTA** [comment]
ok thank you
