### ISSUE TITLE
Solver run by any department 

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [UniTime/unitime#88]
Can any department run solver but not change another rustle department ??

**Comment by tomas-muller** [comment]
Yes, this can be achieved with the Department Schedule Manager roles. Users with this role have only access to courses of their department(s), and if there is a solver group for just their department(s), they can also run the course timetabling solver. More details are available in the Administration manual.

**Comment by Abdulaziz-KTA** [comment]
thank you

**Comment by Abdulaziz-KTA** [comment]
what happens when create two group solver 11 and 2 for the same department  and the first solver to take some resource, is 2 take same room, time, day and Instructors like 1?

**Comment by tomas-muller** [comment]
One department can be present only in one solver group.

**Comment by Abdulaziz-KTA** [comment]
ok.
 what happened to room and time, for example room A23 and day: Sunday, time: 01:00 pm is taken by department 1 solver it will include to department 2 solver or not.

**Comment by tomas-muller** [comment]
The first committed solution will get the space. If the second solver is run after the first has been saved and committed, the room will show as unavailable at the time. That is, the solver will not put the class in a room at a time when there already is some other committed assignment.

**Comment by Abdulaziz-KTA** [comment]
thank you.

**Comment by Abdulaziz-KTA** [comment]
I have many department and many Instructors, and some Instructors teach more 2 department or more.
how do that correct in UinTime ?
Is it should be add  Instructor (name) and (External Id) in every department he teaches?

**Comment by tomas-muller** [comment]
If an instructor is teaching in two departments, there need to be two instructor records -- one for each department (this allows for having different preferences for each department). In this case, please make sure that they have the matching external id (UniTime uses the external id to ensure the instructor does not get to teach overlapping classes).

**Comment by Abdulaziz-KTA** [comment]
![image](https://user-images.githubusercontent.com/46826627/123591061-33717e00-d7f4-11eb-842c-d93043a31efe.png)

is there options to show all name ?

**Comment by tomas-muller** [comment]
Yes, see the "Instructor name display format" in Preferences > Settings. The default can be changed on Administration > Defaults > User Settings.

**Comment by Abdulaziz-KTA** [comment]
Thank you.

**Comment by Abdulaziz-KTA** [comment]
![image](https://user-images.githubusercontent.com/46826627/123635216-19e82a80-d824-11eb-88ef-94aa78c91a23.png)
in Subject Areas is there one Subject Areas in deferent department in image is correct ???

**Comment by Abdulaziz-KTA** [comment]
Is there an option for the students group to belong to the department?

**Comment by tomas-muller** [comment]
There is no direct relationship between student groups and departments.

**Comment by Abdulaziz-KTA** [comment]
Could it happen in the future? add student groups to departments.

**Comment by tomas-muller** [comment]
It is possible, however, there are currently no plans to add such a relation. What would be the purpose?

As far as I know, at most universities (that I know of and have been working with) there is no direct relationship between students and departments. Students are typically associated with their curricula (academic areas, majors, minors, and classifications). While the academic areas (or sometimes majors) may or may not have some relation to individual departments, a student is often allowed to take courses from across multiple departments.

Also, please note, that student groups can be divided by type. You can define various student group types on the Administration > Other > Student Group Types page.

**Comment by Abdulaziz-KTA** [comment]
![image](https://user-images.githubusercontent.com/46826627/129151817-39178284-5bc9-4dba-b55a-06812adb0160.png)

any way to get different  time the same lecture like lec 1,2 and 3 have same time.

**Comment by tomas-muller** [comment]
This question is a duplicate of the one in issue #93.

If a class has a time pattern that meets multiple times a week (e.g., 2 x 50), all meetings of the class are at the same time, and in the same room. Also, both meetings are of the same length. Anything different can be modeled using two or subparts, one for each meeting. Nesting them under each other will ensure that the students will take the correct combination -- e.g., Lec 1 with Lec 1a, Lec 2 with Lec 2a, etc.

Here is an example with a 3 x 50 class that needs to have two meetings on the same day. In this case, each 3 x 50 class was split into one 1 x 50 class and one 2 x 50 class:
![Screen Shot 2015-12-15 at 10 45 18 (1) (1) (1)](https://user-images.githubusercontent.com/10631634/129470392-210666d9-2f38-4049-8fe5-f68e21d18835.png)

Also, the distribution preferences can be used to provide additional structure between the appropriate classes (same days and room in the above example).

Please note the nesting between the two lecture subparts (the second lecture is under the first one). This is to ensure that a student will either take the Lec 1 and Lec 1a combination or the Lec 2 and Lec 2a combination (but not Lec 1 with Lec 2a etc.). It also helps with the distribution preferences (progressive structure will create the constraint only between the nested classes Lec 1 - Lec 1a and between Lec 2 - Lec 2a).
