### ISSUE TITLE
Import the Purdue benchmark data in UniTime

### ISSUE THREAD

**Issue by GuoYuanxinKevin** [UniTime/unitime#90]
How am I supposed to try the Purdue datasets in Unitime (https://www.unitime.org/uct_datasets.php)? I tried importing in the data exchange page but it just prompts Waiting

**Comment by tomas-muller** [comment]
The course timetabling benchmark datasets **cannot** be imported into UniTime. They are in the format that is used by the constraint solver (see [here](https://www.unitime.org/uct_dataformat_v24.php)) and only contain the information that is needed by the solver (see [here](https://www.unitime.org/uct_execution.php)). They are anonymized and do not have enough information -- for example, in UniTime you can set preferences and requirements on different levels, but the solver file only contains a list of available rooms and times for each class with the preferences translated into penalties.

The purpose of these data sets is for other researchers to be able to replicate our results and possibly to use the data sets in their own research, building their own solver algorithms. If you are interested in this, please take a look at the International Timetabling Competition ([www.itc2019.org](https://www.itc2019.org)) that we have co-organized.

**Comment by GuoYuanxinKevin** [comment]
Thanks so much! 

One more question, if I want to use UniTime for the course scheduling problem for my university, should I manually enter the data via the interface?

**Comment by tomas-muller** [comment]
A lot of the data can be imported using the XML interfaces described at [www.unitime.org/uct_interfaces.php](https://www.unitime.org/uct_interfaces.php).

But it is also possible to enter most of the data through the UniTime user interface (all except students and their course demands or last-like demands -- though, it is possible to build the course timetable without that, using curricula instead).
