### ISSUE TITLE
Hibernate Exception When Updating an Instructor Info (PostgreSQL)

### ISSUE THREAD

**Issue by Kibele** [UniTime/unitime#91]
The following error can be reproduced in demo data with PostgreSQL setup. Simply go to a instructorInfoEdit page and hit the Update button.

<span class="unitime-Page"><span class="row"><span class="main"><span class="body" id="unitime-Page">

Error:  						could not extract ResultSet
--
Trace: | org.hibernate.exception.SQLGrammarException: could not extract ResultSet 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123) 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126) 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112) 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:91) 	at org.hibernate.loader.Loader.getResultSet(Loader.java:2066) 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1863) 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1839) 	at org.hibernate.loader.Loader.doQuery(Loader.java:910) 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355) 	at org.hibernate.loader.Loader.doList(Loader.java:2554) 	at org.hibernate.loader.Loader.doList(Loader.java:2540) 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370) 	at org.hibernate.loader.Loader.list(Loader.java:2365) 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:497) 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387) 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:236) 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1300) 	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103) 	at org.unitime.timetable.action.InstructorAction.isDeptInstructorUnique(InstructorAction.java:320) 	at org.unitime.timetable.action.InstructorInfoEditAction.execute(InstructorInfoEditAction.java:138) 	at org.springframework.web.struts.DelegatingActionProxy.execute(DelegatingActionProxy.java:113) 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425) 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228) 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913) 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.unitime.timetable.filter.BusySessions$Filter.doFilter(BusySessions.java:85) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.unitime.timetable.filter.LocaleFilter.doFilter(LocaleFilter.java:87) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.unitime.timetable.filter.QueryLogFilter.doFilter(QueryLogFilter.java:118) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.unitime.timetable.filter.PageAccessFilter.doFilter(PageAccessFilter.java:164) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.unitime.timetable.filter.MessageLogFilter.doFilter(MessageLogFilter.java:93) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at  org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at  org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at  org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at  org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at  org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at  org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.unitime.timetable.filter.HibSessionFilter.doFilter(HibSessionFilter.java:70) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.unitime.timetable.filter.EncodingFilter.doFilter(EncodingFilter.java:50) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 	at java.base/java.lang.Thread.run(Thread.java:829) Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: bigint <> character varying   Hint: No operator matches the given name and argument types. You might need to add explicit type casts.   Position: 1023 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552) 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284) 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322) 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114) 	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) 	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:82) 	... 101 more

</span></span></span></span>

**Comment by Kibele** [comment]
I've just pulled the recent changes and compiled UniTime. It works as expected. Thank you very much.

**Comment by tomas-muller** [comment]
Thank you. The fix will also appear in our [nightly builds](https://builds.unitime.org) starting 
- UniTime 4.4 build 149,
- UniTime 4.5 build 174, and
- UniTime 4.6 build 19.

Unfortunately, ProgresSQL is more strict when it comes to query parameters as Oracle or MySQL that we have been using in our development and testing from the start.
